Added verbosity
outstand/docker-nfs-client pull request #5
Opened 2018-06-08 17:28 UTC by cron410

Verbosity in the mount command allows for better logging.

2018-06-08 18:25 UTC, ryansch requested changes

2018-06-08 18:25 UTC, ryansch commented on docker-entrypoint.sh
> +mount -vvv -t "$FSTYPE" -o "$MOUNT_OPTIONS" "$SERVER:$SHARE" "$MOUNTPOINT"
There's no indication in the man page that repeating v's will increase the verbosity like with the `ssh` command.

2018-09-21 12:49 UTC, cron410 commented
Changed it to a single v

2018-09-22 03:49 UTC, ryansch approved these changes

2018-09-22 03:49 UTC, merged